# Generated by Django 5.0.6 on 2024-06-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='rating',
            field=models.BooleanField(default=True),
        ),
    ]
