# Generated by Django 5.0.6 on 2024-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_demomodel_gender_alter_demomodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('d_rating', models.CharField(choices=[('G', 'Good'), ('M', 'Moderate'), ('B', 'Bad')], max_length=1)),
                ('t_rating', models.CharField(choices=[('G', 'Good'), ('M', 'Moderate'), ('B', 'Bad')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='demoModel',
        ),
    ]
